// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moderators.proto

package io.grpc.examples.moderators;

public final class CreatePollOuter {
  private CreatePollOuter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_example_moderator_Poll_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_grpc_example_moderator_Poll_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_example_moderator_Poll_choice_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_grpc_example_moderator_Poll_choice_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_example_moderator_PollDetails_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_grpc_example_moderator_PollDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_example_moderator_PollDetails_choice_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_grpc_example_moderator_PollDetails_choice_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020moderators.proto\022\026grpc.example.moderat" +
      "or\"\225\001\n\004Poll\022\020\n\010question\030\001 \001(\t\022\022\n\nstarted" +
      "_at\030\002 \001(\t\022\022\n\nexpired_at\030\003 \001(\t\0229\n\014choices" +
      "_poll\030\004 \003(\0132#.grpc.example.moderator.Pol" +
      "l.choice\032\030\n\006choice\022\016\n\006result\030\001 \001(\t\"\256\001\n\013P" +
      "ollDetails\022\020\n\010question\030\001 \001(\t\022\022\n\nstarted_" +
      "at\030\002 \001(\t\022\022\n\nexpired_at\030\003 \001(\t\022?\n\013choice_p" +
      "oll\030\004 \003(\0132*.grpc.example.moderator.PollD" +
      "etails.choice\022\n\n\002id\030\005 \001(\005\032\030\n\006choice\022\016\n\006r" +
      "esult\030\001 \001(\t2_\n\nCreatePoll\022Q\n\ncreatePoll\022",
      "#.grpc.example.moderator.PollDetails\032\034.g" +
      "rpc.example.moderator.Poll\"\000B0\n\033io.grpc." +
      "examples.moderatorsB\017CreatePollOuterP\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_grpc_example_moderator_Poll_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_example_moderator_Poll_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_grpc_example_moderator_Poll_descriptor,
        new java.lang.String[] { "Question", "StartedAt", "ExpiredAt", "ChoicesPoll", });
    internal_static_grpc_example_moderator_Poll_choice_descriptor =
      internal_static_grpc_example_moderator_Poll_descriptor.getNestedTypes().get(0);
    internal_static_grpc_example_moderator_Poll_choice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_grpc_example_moderator_Poll_choice_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_grpc_example_moderator_PollDetails_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_example_moderator_PollDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_grpc_example_moderator_PollDetails_descriptor,
        new java.lang.String[] { "Question", "StartedAt", "ExpiredAt", "ChoicePoll", "Id", });
    internal_static_grpc_example_moderator_PollDetails_choice_descriptor =
      internal_static_grpc_example_moderator_PollDetails_descriptor.getNestedTypes().get(0);
    internal_static_grpc_example_moderator_PollDetails_choice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_grpc_example_moderator_PollDetails_choice_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
