// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moderators.proto

package io.grpc.examples.moderators;

public interface PollDetailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.example.moderator.PollDetails)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string question = 1;</code>
   */
  java.lang.String getQuestion();
  /**
   * <code>optional string question = 1;</code>
   */
  com.google.protobuf.ByteString
      getQuestionBytes();

  /**
   * <code>optional string started_at = 2;</code>
   */
  java.lang.String getStartedAt();
  /**
   * <code>optional string started_at = 2;</code>
   */
  com.google.protobuf.ByteString
      getStartedAtBytes();

  /**
   * <code>optional string expired_at = 3;</code>
   */
  java.lang.String getExpiredAt();
  /**
   * <code>optional string expired_at = 3;</code>
   */
  com.google.protobuf.ByteString
      getExpiredAtBytes();

  /**
   * <code>repeated .grpc.example.moderator.PollDetails.choice choice_poll = 4;</code>
   */
  java.util.List<io.grpc.examples.moderators.PollDetails.choice> 
      getChoicePollList();
  /**
   * <code>repeated .grpc.example.moderator.PollDetails.choice choice_poll = 4;</code>
   */
  io.grpc.examples.moderators.PollDetails.choice getChoicePoll(int index);
  /**
   * <code>repeated .grpc.example.moderator.PollDetails.choice choice_poll = 4;</code>
   */
  int getChoicePollCount();
  /**
   * <code>repeated .grpc.example.moderator.PollDetails.choice choice_poll = 4;</code>
   */
  java.util.List<? extends io.grpc.examples.moderators.PollDetails.choiceOrBuilder> 
      getChoicePollOrBuilderList();
  /**
   * <code>repeated .grpc.example.moderator.PollDetails.choice choice_poll = 4;</code>
   */
  io.grpc.examples.moderators.PollDetails.choiceOrBuilder getChoicePollOrBuilder(
      int index);

  /**
   * <code>optional int32 id = 5;</code>
   */
  int getId();
}
