// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moderators.proto

package io.grpc.examples.moderators;

/**
 * Protobuf type {@code grpc.example.moderator.PollDetails}
 */
public  final class PollDetails extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:grpc.example.moderator.PollDetails)
    PollDetailsOrBuilder {
  // Use PollDetails.newBuilder() to construct.
  private PollDetails(com.google.protobuf.GeneratedMessage.Builder builder) {
    super(builder);
  }
  private PollDetails() {
    question_ = "";
    startedAt_ = "";
    expiredAt_ = "";
    choicePoll_ = java.util.Collections.emptyList();
    id_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private PollDetails(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();

            question_ = bs;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();

            startedAt_ = bs;
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();

            expiredAt_ = bs;
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              choicePoll_ = new java.util.ArrayList<io.grpc.examples.moderators.PollDetails.choice>();
              mutable_bitField0_ |= 0x00000008;
            }
            choicePoll_.add(input.readMessage(io.grpc.examples.moderators.PollDetails.choice.PARSER, extensionRegistry));
            break;
          }
          case 40: {

            id_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        choicePoll_ = java.util.Collections.unmodifiableList(choicePoll_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.grpc.examples.moderators.CreatePollOuter.internal_static_grpc_example_moderator_PollDetails_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.grpc.examples.moderators.CreatePollOuter.internal_static_grpc_example_moderator_PollDetails_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.grpc.examples.moderators.PollDetails.class, io.grpc.examples.moderators.PollDetails.Builder.class);
  }

  public static final com.google.protobuf.Parser<PollDetails> PARSER =
      new com.google.protobuf.AbstractParser<PollDetails>() {
    public PollDetails parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PollDetails(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<PollDetails> getParserForType() {
    return PARSER;
  }

  public interface choiceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:grpc.example.moderator.PollDetails.choice)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string result = 1;</code>
     */
    java.lang.String getResult();
    /**
     * <code>optional string result = 1;</code>
     */
    com.google.protobuf.ByteString
        getResultBytes();
  }
  /**
   * Protobuf type {@code grpc.example.moderator.PollDetails.choice}
   */
  public  static final class choice extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:grpc.example.moderator.PollDetails.choice)
      choiceOrBuilder {
    // Use choice.newBuilder() to construct.
    private choice(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private choice() {
      result_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private choice(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();

              result_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.examples.moderators.CreatePollOuter.internal_static_grpc_example_moderator_PollDetails_choice_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.examples.moderators.CreatePollOuter.internal_static_grpc_example_moderator_PollDetails_choice_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.examples.moderators.PollDetails.choice.class, io.grpc.examples.moderators.PollDetails.choice.Builder.class);
    }

    public static final com.google.protobuf.Parser<choice> PARSER =
        new com.google.protobuf.AbstractParser<choice>() {
      public choice parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new choice(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<choice> getParserForType() {
      return PARSER;
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private java.lang.Object result_;
    /**
     * <code>optional string result = 1;</code>
     */
    public java.lang.String getResult() {
      java.lang.Object ref = result_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          result_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string result = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResultBytes() {
      java.lang.Object ref = result_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        result_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!getResultBytes().isEmpty()) {
        output.writeBytes(1, getResultBytes());
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!getResultBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getResultBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static io.grpc.examples.moderators.PollDetails.choice parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.examples.moderators.PollDetails.choice parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.examples.moderators.PollDetails.choice parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.examples.moderators.PollDetails.choice parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.examples.moderators.PollDetails.choice parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.grpc.examples.moderators.PollDetails.choice parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.grpc.examples.moderators.PollDetails.choice parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.grpc.examples.moderators.PollDetails.choice parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.grpc.examples.moderators.PollDetails.choice parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.grpc.examples.moderators.PollDetails.choice parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(io.grpc.examples.moderators.PollDetails.choice prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code grpc.example.moderator.PollDetails.choice}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:grpc.example.moderator.PollDetails.choice)
        io.grpc.examples.moderators.PollDetails.choiceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.grpc.examples.moderators.CreatePollOuter.internal_static_grpc_example_moderator_PollDetails_choice_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.grpc.examples.moderators.CreatePollOuter.internal_static_grpc_example_moderator_PollDetails_choice_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.grpc.examples.moderators.PollDetails.choice.class, io.grpc.examples.moderators.PollDetails.choice.Builder.class);
      }

      // Construct using io.grpc.examples.moderators.PollDetails.choice.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        result_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.grpc.examples.moderators.CreatePollOuter.internal_static_grpc_example_moderator_PollDetails_choice_descriptor;
      }

      public io.grpc.examples.moderators.PollDetails.choice getDefaultInstanceForType() {
        return io.grpc.examples.moderators.PollDetails.choice.getDefaultInstance();
      }

      public io.grpc.examples.moderators.PollDetails.choice build() {
        io.grpc.examples.moderators.PollDetails.choice result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.grpc.examples.moderators.PollDetails.choice buildPartial() {
        io.grpc.examples.moderators.PollDetails.choice result = new io.grpc.examples.moderators.PollDetails.choice(this);
        result.result_ = result_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.grpc.examples.moderators.PollDetails.choice) {
          return mergeFrom((io.grpc.examples.moderators.PollDetails.choice)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.grpc.examples.moderators.PollDetails.choice other) {
        if (other == io.grpc.examples.moderators.PollDetails.choice.getDefaultInstance()) return this;
        if (!other.getResult().isEmpty()) {
          result_ = other.result_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.grpc.examples.moderators.PollDetails.choice parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.grpc.examples.moderators.PollDetails.choice) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object result_ = "";
      /**
       * <code>optional string result = 1;</code>
       */
      public java.lang.String getResult() {
        java.lang.Object ref = result_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            result_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string result = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResultBytes() {
        java.lang.Object ref = result_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          result_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string result = 1;</code>
       */
      public Builder setResult(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string result = 1;</code>
       */
      public Builder clearResult() {
        
        result_ = getDefaultInstance().getResult();
        onChanged();
        return this;
      }
      /**
       * <code>optional string result = 1;</code>
       */
      public Builder setResultBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        result_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:grpc.example.moderator.PollDetails.choice)
    }

    // @@protoc_insertion_point(class_scope:grpc.example.moderator.PollDetails.choice)
    private static final io.grpc.examples.moderators.PollDetails.choice defaultInstance;static {
      defaultInstance = new io.grpc.examples.moderators.PollDetails.choice();
    }

    public static io.grpc.examples.moderators.PollDetails.choice getDefaultInstance() {
      return defaultInstance;
    }

    public io.grpc.examples.moderators.PollDetails.choice getDefaultInstanceForType() {
      return defaultInstance;
    }

  }

  private int bitField0_;
  public static final int QUESTION_FIELD_NUMBER = 1;
  private java.lang.Object question_;
  /**
   * <code>optional string question = 1;</code>
   */
  public java.lang.String getQuestion() {
    java.lang.Object ref = question_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        question_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string question = 1;</code>
   */
  public com.google.protobuf.ByteString
      getQuestionBytes() {
    java.lang.Object ref = question_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      question_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STARTED_AT_FIELD_NUMBER = 2;
  private java.lang.Object startedAt_;
  /**
   * <code>optional string started_at = 2;</code>
   */
  public java.lang.String getStartedAt() {
    java.lang.Object ref = startedAt_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        startedAt_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string started_at = 2;</code>
   */
  public com.google.protobuf.ByteString
      getStartedAtBytes() {
    java.lang.Object ref = startedAt_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      startedAt_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXPIRED_AT_FIELD_NUMBER = 3;
  private java.lang.Object expiredAt_;
  /**
   * <code>optional string expired_at = 3;</code>
   */
  public java.lang.String getExpiredAt() {
    java.lang.Object ref = expiredAt_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        expiredAt_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string expired_at = 3;</code>
   */
  public com.google.protobuf.ByteString
      getExpiredAtBytes() {
    java.lang.Object ref = expiredAt_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      expiredAt_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHOICE_POLL_FIELD_NUMBER = 4;
  private java.util.List<io.grpc.examples.moderators.PollDetails.choice> choicePoll_;
  /**
   * <code>repeated .grpc.example.moderator.PollDetails.choice choice_poll = 4;</code>
   */
  public java.util.List<io.grpc.examples.moderators.PollDetails.choice> getChoicePollList() {
    return choicePoll_;
  }
  /**
   * <code>repeated .grpc.example.moderator.PollDetails.choice choice_poll = 4;</code>
   */
  public java.util.List<? extends io.grpc.examples.moderators.PollDetails.choiceOrBuilder> 
      getChoicePollOrBuilderList() {
    return choicePoll_;
  }
  /**
   * <code>repeated .grpc.example.moderator.PollDetails.choice choice_poll = 4;</code>
   */
  public int getChoicePollCount() {
    return choicePoll_.size();
  }
  /**
   * <code>repeated .grpc.example.moderator.PollDetails.choice choice_poll = 4;</code>
   */
  public io.grpc.examples.moderators.PollDetails.choice getChoicePoll(int index) {
    return choicePoll_.get(index);
  }
  /**
   * <code>repeated .grpc.example.moderator.PollDetails.choice choice_poll = 4;</code>
   */
  public io.grpc.examples.moderators.PollDetails.choiceOrBuilder getChoicePollOrBuilder(
      int index) {
    return choicePoll_.get(index);
  }

  public static final int ID_FIELD_NUMBER = 5;
  private int id_;
  /**
   * <code>optional int32 id = 5;</code>
   */
  public int getId() {
    return id_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!getQuestionBytes().isEmpty()) {
      output.writeBytes(1, getQuestionBytes());
    }
    if (!getStartedAtBytes().isEmpty()) {
      output.writeBytes(2, getStartedAtBytes());
    }
    if (!getExpiredAtBytes().isEmpty()) {
      output.writeBytes(3, getExpiredAtBytes());
    }
    for (int i = 0; i < choicePoll_.size(); i++) {
      output.writeMessage(4, choicePoll_.get(i));
    }
    if (id_ != 0) {
      output.writeInt32(5, id_);
    }
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (!getQuestionBytes().isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getQuestionBytes());
    }
    if (!getStartedAtBytes().isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getStartedAtBytes());
    }
    if (!getExpiredAtBytes().isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, getExpiredAtBytes());
    }
    for (int i = 0; i < choicePoll_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, choicePoll_.get(i));
    }
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, id_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static io.grpc.examples.moderators.PollDetails parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.examples.moderators.PollDetails parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.examples.moderators.PollDetails parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.examples.moderators.PollDetails parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.examples.moderators.PollDetails parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static io.grpc.examples.moderators.PollDetails parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static io.grpc.examples.moderators.PollDetails parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static io.grpc.examples.moderators.PollDetails parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static io.grpc.examples.moderators.PollDetails parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static io.grpc.examples.moderators.PollDetails parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return new Builder(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(io.grpc.examples.moderators.PollDetails prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpc.example.moderator.PollDetails}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.example.moderator.PollDetails)
      io.grpc.examples.moderators.PollDetailsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.examples.moderators.CreatePollOuter.internal_static_grpc_example_moderator_PollDetails_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.examples.moderators.CreatePollOuter.internal_static_grpc_example_moderator_PollDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.examples.moderators.PollDetails.class, io.grpc.examples.moderators.PollDetails.Builder.class);
    }

    // Construct using io.grpc.examples.moderators.PollDetails.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getChoicePollFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      question_ = "";

      startedAt_ = "";

      expiredAt_ = "";

      if (choicePollBuilder_ == null) {
        choicePoll_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        choicePollBuilder_.clear();
      }
      id_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.grpc.examples.moderators.CreatePollOuter.internal_static_grpc_example_moderator_PollDetails_descriptor;
    }

    public io.grpc.examples.moderators.PollDetails getDefaultInstanceForType() {
      return io.grpc.examples.moderators.PollDetails.getDefaultInstance();
    }

    public io.grpc.examples.moderators.PollDetails build() {
      io.grpc.examples.moderators.PollDetails result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.grpc.examples.moderators.PollDetails buildPartial() {
      io.grpc.examples.moderators.PollDetails result = new io.grpc.examples.moderators.PollDetails(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.question_ = question_;
      result.startedAt_ = startedAt_;
      result.expiredAt_ = expiredAt_;
      if (choicePollBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          choicePoll_ = java.util.Collections.unmodifiableList(choicePoll_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.choicePoll_ = choicePoll_;
      } else {
        result.choicePoll_ = choicePollBuilder_.build();
      }
      result.id_ = id_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.grpc.examples.moderators.PollDetails) {
        return mergeFrom((io.grpc.examples.moderators.PollDetails)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.grpc.examples.moderators.PollDetails other) {
      if (other == io.grpc.examples.moderators.PollDetails.getDefaultInstance()) return this;
      if (!other.getQuestion().isEmpty()) {
        question_ = other.question_;
        onChanged();
      }
      if (!other.getStartedAt().isEmpty()) {
        startedAt_ = other.startedAt_;
        onChanged();
      }
      if (!other.getExpiredAt().isEmpty()) {
        expiredAt_ = other.expiredAt_;
        onChanged();
      }
      if (choicePollBuilder_ == null) {
        if (!other.choicePoll_.isEmpty()) {
          if (choicePoll_.isEmpty()) {
            choicePoll_ = other.choicePoll_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureChoicePollIsMutable();
            choicePoll_.addAll(other.choicePoll_);
          }
          onChanged();
        }
      } else {
        if (!other.choicePoll_.isEmpty()) {
          if (choicePollBuilder_.isEmpty()) {
            choicePollBuilder_.dispose();
            choicePollBuilder_ = null;
            choicePoll_ = other.choicePoll_;
            bitField0_ = (bitField0_ & ~0x00000008);
            choicePollBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getChoicePollFieldBuilder() : null;
          } else {
            choicePollBuilder_.addAllMessages(other.choicePoll_);
          }
        }
      }
      if (other.getId() != 0) {
        setId(other.getId());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.grpc.examples.moderators.PollDetails parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.grpc.examples.moderators.PollDetails) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object question_ = "";
    /**
     * <code>optional string question = 1;</code>
     */
    public java.lang.String getQuestion() {
      java.lang.Object ref = question_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          question_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string question = 1;</code>
     */
    public com.google.protobuf.ByteString
        getQuestionBytes() {
      java.lang.Object ref = question_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        question_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string question = 1;</code>
     */
    public Builder setQuestion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      question_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string question = 1;</code>
     */
    public Builder clearQuestion() {
      
      question_ = getDefaultInstance().getQuestion();
      onChanged();
      return this;
    }
    /**
     * <code>optional string question = 1;</code>
     */
    public Builder setQuestionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      question_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object startedAt_ = "";
    /**
     * <code>optional string started_at = 2;</code>
     */
    public java.lang.String getStartedAt() {
      java.lang.Object ref = startedAt_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          startedAt_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string started_at = 2;</code>
     */
    public com.google.protobuf.ByteString
        getStartedAtBytes() {
      java.lang.Object ref = startedAt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        startedAt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string started_at = 2;</code>
     */
    public Builder setStartedAt(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      startedAt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string started_at = 2;</code>
     */
    public Builder clearStartedAt() {
      
      startedAt_ = getDefaultInstance().getStartedAt();
      onChanged();
      return this;
    }
    /**
     * <code>optional string started_at = 2;</code>
     */
    public Builder setStartedAtBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      startedAt_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object expiredAt_ = "";
    /**
     * <code>optional string expired_at = 3;</code>
     */
    public java.lang.String getExpiredAt() {
      java.lang.Object ref = expiredAt_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          expiredAt_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string expired_at = 3;</code>
     */
    public com.google.protobuf.ByteString
        getExpiredAtBytes() {
      java.lang.Object ref = expiredAt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        expiredAt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string expired_at = 3;</code>
     */
    public Builder setExpiredAt(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      expiredAt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string expired_at = 3;</code>
     */
    public Builder clearExpiredAt() {
      
      expiredAt_ = getDefaultInstance().getExpiredAt();
      onChanged();
      return this;
    }
    /**
     * <code>optional string expired_at = 3;</code>
     */
    public Builder setExpiredAtBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      expiredAt_ = value;
      onChanged();
      return this;
    }

    private java.util.List<io.grpc.examples.moderators.PollDetails.choice> choicePoll_ =
      java.util.Collections.emptyList();
    private void ensureChoicePollIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        choicePoll_ = new java.util.ArrayList<io.grpc.examples.moderators.PollDetails.choice>(choicePoll_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        io.grpc.examples.moderators.PollDetails.choice, io.grpc.examples.moderators.PollDetails.choice.Builder, io.grpc.examples.moderators.PollDetails.choiceOrBuilder> choicePollBuilder_;

    /**
     * <code>repeated .grpc.example.moderator.PollDetails.choice choice_poll = 4;</code>
     */
    public java.util.List<io.grpc.examples.moderators.PollDetails.choice> getChoicePollList() {
      if (choicePollBuilder_ == null) {
        return java.util.Collections.unmodifiableList(choicePoll_);
      } else {
        return choicePollBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .grpc.example.moderator.PollDetails.choice choice_poll = 4;</code>
     */
    public int getChoicePollCount() {
      if (choicePollBuilder_ == null) {
        return choicePoll_.size();
      } else {
        return choicePollBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .grpc.example.moderator.PollDetails.choice choice_poll = 4;</code>
     */
    public io.grpc.examples.moderators.PollDetails.choice getChoicePoll(int index) {
      if (choicePollBuilder_ == null) {
        return choicePoll_.get(index);
      } else {
        return choicePollBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .grpc.example.moderator.PollDetails.choice choice_poll = 4;</code>
     */
    public Builder setChoicePoll(
        int index, io.grpc.examples.moderators.PollDetails.choice value) {
      if (choicePollBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChoicePollIsMutable();
        choicePoll_.set(index, value);
        onChanged();
      } else {
        choicePollBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.example.moderator.PollDetails.choice choice_poll = 4;</code>
     */
    public Builder setChoicePoll(
        int index, io.grpc.examples.moderators.PollDetails.choice.Builder builderForValue) {
      if (choicePollBuilder_ == null) {
        ensureChoicePollIsMutable();
        choicePoll_.set(index, builderForValue.build());
        onChanged();
      } else {
        choicePollBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpc.example.moderator.PollDetails.choice choice_poll = 4;</code>
     */
    public Builder addChoicePoll(io.grpc.examples.moderators.PollDetails.choice value) {
      if (choicePollBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChoicePollIsMutable();
        choicePoll_.add(value);
        onChanged();
      } else {
        choicePollBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.example.moderator.PollDetails.choice choice_poll = 4;</code>
     */
    public Builder addChoicePoll(
        int index, io.grpc.examples.moderators.PollDetails.choice value) {
      if (choicePollBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChoicePollIsMutable();
        choicePoll_.add(index, value);
        onChanged();
      } else {
        choicePollBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.example.moderator.PollDetails.choice choice_poll = 4;</code>
     */
    public Builder addChoicePoll(
        io.grpc.examples.moderators.PollDetails.choice.Builder builderForValue) {
      if (choicePollBuilder_ == null) {
        ensureChoicePollIsMutable();
        choicePoll_.add(builderForValue.build());
        onChanged();
      } else {
        choicePollBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpc.example.moderator.PollDetails.choice choice_poll = 4;</code>
     */
    public Builder addChoicePoll(
        int index, io.grpc.examples.moderators.PollDetails.choice.Builder builderForValue) {
      if (choicePollBuilder_ == null) {
        ensureChoicePollIsMutable();
        choicePoll_.add(index, builderForValue.build());
        onChanged();
      } else {
        choicePollBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpc.example.moderator.PollDetails.choice choice_poll = 4;</code>
     */
    public Builder addAllChoicePoll(
        java.lang.Iterable<? extends io.grpc.examples.moderators.PollDetails.choice> values) {
      if (choicePollBuilder_ == null) {
        ensureChoicePollIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, choicePoll_);
        onChanged();
      } else {
        choicePollBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.example.moderator.PollDetails.choice choice_poll = 4;</code>
     */
    public Builder clearChoicePoll() {
      if (choicePollBuilder_ == null) {
        choicePoll_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        choicePollBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .grpc.example.moderator.PollDetails.choice choice_poll = 4;</code>
     */
    public Builder removeChoicePoll(int index) {
      if (choicePollBuilder_ == null) {
        ensureChoicePollIsMutable();
        choicePoll_.remove(index);
        onChanged();
      } else {
        choicePollBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.example.moderator.PollDetails.choice choice_poll = 4;</code>
     */
    public io.grpc.examples.moderators.PollDetails.choice.Builder getChoicePollBuilder(
        int index) {
      return getChoicePollFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .grpc.example.moderator.PollDetails.choice choice_poll = 4;</code>
     */
    public io.grpc.examples.moderators.PollDetails.choiceOrBuilder getChoicePollOrBuilder(
        int index) {
      if (choicePollBuilder_ == null) {
        return choicePoll_.get(index);  } else {
        return choicePollBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .grpc.example.moderator.PollDetails.choice choice_poll = 4;</code>
     */
    public java.util.List<? extends io.grpc.examples.moderators.PollDetails.choiceOrBuilder> 
         getChoicePollOrBuilderList() {
      if (choicePollBuilder_ != null) {
        return choicePollBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(choicePoll_);
      }
    }
    /**
     * <code>repeated .grpc.example.moderator.PollDetails.choice choice_poll = 4;</code>
     */
    public io.grpc.examples.moderators.PollDetails.choice.Builder addChoicePollBuilder() {
      return getChoicePollFieldBuilder().addBuilder(
          io.grpc.examples.moderators.PollDetails.choice.getDefaultInstance());
    }
    /**
     * <code>repeated .grpc.example.moderator.PollDetails.choice choice_poll = 4;</code>
     */
    public io.grpc.examples.moderators.PollDetails.choice.Builder addChoicePollBuilder(
        int index) {
      return getChoicePollFieldBuilder().addBuilder(
          index, io.grpc.examples.moderators.PollDetails.choice.getDefaultInstance());
    }
    /**
     * <code>repeated .grpc.example.moderator.PollDetails.choice choice_poll = 4;</code>
     */
    public java.util.List<io.grpc.examples.moderators.PollDetails.choice.Builder> 
         getChoicePollBuilderList() {
      return getChoicePollFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        io.grpc.examples.moderators.PollDetails.choice, io.grpc.examples.moderators.PollDetails.choice.Builder, io.grpc.examples.moderators.PollDetails.choiceOrBuilder> 
        getChoicePollFieldBuilder() {
      if (choicePollBuilder_ == null) {
        choicePollBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            io.grpc.examples.moderators.PollDetails.choice, io.grpc.examples.moderators.PollDetails.choice.Builder, io.grpc.examples.moderators.PollDetails.choiceOrBuilder>(
                choicePoll_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        choicePoll_ = null;
      }
      return choicePollBuilder_;
    }

    private int id_ ;
    /**
     * <code>optional int32 id = 5;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>optional int32 id = 5;</code>
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 id = 5;</code>
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:grpc.example.moderator.PollDetails)
  }

  // @@protoc_insertion_point(class_scope:grpc.example.moderator.PollDetails)
  private static final io.grpc.examples.moderators.PollDetails defaultInstance;static {
    defaultInstance = new io.grpc.examples.moderators.PollDetails();
  }

  public static io.grpc.examples.moderators.PollDetails getDefaultInstance() {
    return defaultInstance;
  }

  public io.grpc.examples.moderators.PollDetails getDefaultInstanceForType() {
    return defaultInstance;
  }

}

