// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moderators.proto

package io.grpc.examples.moderators;

public interface PollOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.example.moderator.Poll)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string question = 1;</code>
   */
  java.lang.String getQuestion();
  /**
   * <code>optional string question = 1;</code>
   */
  com.google.protobuf.ByteString
      getQuestionBytes();

  /**
   * <code>optional string started_at = 2;</code>
   */
  java.lang.String getStartedAt();
  /**
   * <code>optional string started_at = 2;</code>
   */
  com.google.protobuf.ByteString
      getStartedAtBytes();

  /**
   * <code>optional string expired_at = 3;</code>
   */
  java.lang.String getExpiredAt();
  /**
   * <code>optional string expired_at = 3;</code>
   */
  com.google.protobuf.ByteString
      getExpiredAtBytes();

  /**
   * <code>repeated .grpc.example.moderator.Poll.choice choices_poll = 4;</code>
   */
  java.util.List<io.grpc.examples.moderators.Poll.choice> 
      getChoicesPollList();
  /**
   * <code>repeated .grpc.example.moderator.Poll.choice choices_poll = 4;</code>
   */
  io.grpc.examples.moderators.Poll.choice getChoicesPoll(int index);
  /**
   * <code>repeated .grpc.example.moderator.Poll.choice choices_poll = 4;</code>
   */
  int getChoicesPollCount();
  /**
   * <code>repeated .grpc.example.moderator.Poll.choice choices_poll = 4;</code>
   */
  java.util.List<? extends io.grpc.examples.moderators.Poll.choiceOrBuilder> 
      getChoicesPollOrBuilderList();
  /**
   * <code>repeated .grpc.example.moderator.Poll.choice choices_poll = 4;</code>
   */
  io.grpc.examples.moderators.Poll.choiceOrBuilder getChoicesPollOrBuilder(
      int index);
}
